services:
  - type: web
    name: schoolstation-api
    env: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn SchoolStation.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: schoolstation-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
  - type: postgres
    name: schoolstation-db
    databaseName: schoolstationdb
    user: schoolstationuser