# Generated by Django 5.1.6 on 2025-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DATT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.IntegerField(max_length=3, unique=True)),
                ("CO", models.CharField(max_length=8)),
                ("HUM", models.CharField(max_length=3)),
                ("TEMP", models.CharField(max_length=4)),
                ("time", models.TimeField(auto_now=True)),
            ],
        ),
    ]
