# Generated by Django 5.1.6 on 2025-03-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datt",
            name="room",
            field=models.IntegerField(unique=True),
        ),
    ]
