# Generated by Django 5.2.1 on 2025-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_datt_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="datt",
            name="addr",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
