# Generated by Django 5.2.1 on 2025-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_datt_addr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datt",
            name="addr",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="datt",
            name="room",
            field=models.IntegerField(),
        ),
    ]
